version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finalproject_app
     #command: gunicorn logistics_project.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - migrate

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py migrate
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  static_volume:
  media_volume: