# Generated by Django 5.2.8 on 2025-11-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0002_teamevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamevent',
            options={'ordering': ['date', 'start_time', 'created_at']},
        ),
        migrations.AddField(
            model_name='teamevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamevent',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
