# Generated by Django 5.2.8 on 2025-11-20 02:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0004_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='author',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='is_pinned',
        ),
        migrations.AddField(
            model_name='announcement',
            name='author_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Anonymous', max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sams.announcement')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
