# Generated by Django 5.2.8 on 2025-12-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0006_student_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='present',
            field=models.BooleanField(default=True),
        ),
    ]
