# Generated by Django 5.2.7 on 2025-10-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeowner_name', models.CharField(max_length=255)),
                ('home_age', models.PositiveIntegerField()),
                ('climate_zone', models.CharField(choices=[('Humid continental', 'Humid continental'), ('Humid subtropical', 'Humid subtropical'), ('Mediterranean', 'Mediterranean'), ('Oceanic (Marine west coast)', 'Oceanic (Marine west coast)'), ('Desert', 'Desert'), ('Semi-arid', 'Semi-arid'), ('Subarctic', 'Subarctic'), ('Tundra', 'Tundra'), ('Ice cap', 'Ice cap'), ('Tropical', 'Tropical'), ('Highland/Alpine', 'Highland/Alpine')], max_length=50)),
                ('number_of_appliances', models.PositiveIntegerField()),
            ],
        ),
    ]
