# Generated by Django 5.2.7 on 2025-10-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homedetails',
            name='home_age',
        ),
        migrations.AddField(
            model_name='homedetails',
            name='year_built',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
