# Generated by Django 5.2.7 on 2025-10-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_homedetails_home_age_homedetails_year_built'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
