# Generated by Django 5.2.7 on 2025-10-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_homedetails_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homedetails',
            name='homeowner_name',
        ),
        migrations.AddField(
            model_name='homedetails',
            name='building_method',
            field=models.CharField(choices=[('On-site construction (Stick-built)', 'On-site construction (Stick-built)'), ('Modular construction', 'Modular construction'), ('Panelized construction', 'Panelized construction'), ('3D-printed construction', '3D-printed construction')], default='Blank', max_length=50),
        ),
        migrations.AddField(
            model_name='homedetails',
            name='primary_building_material',
            field=models.CharField(choices=[('Wood frame', 'Wood frame'), ('Log or timber frame', 'Log or timber frame'), ('Steel frame', 'Steel frame'), ('Concrete masonry units (CMUs or blocks)', 'Concrete masonry units (CMUs or blocks)'), ('Insulated Concrete Forms (ICFs)', 'Insulated Concrete Forms (ICFs)'), ('Masonry (Brick or stone)', 'Masonry (Brick or stone)'), ('Alternative materials (Straw bale, cob, rammed earth)', 'Alternative materials (Straw bale, cob, rammed earth)')], default='Blank', max_length=250),
        ),
        migrations.AddField(
            model_name='homedetails',
            name='username',
            field=models.CharField(default='Blank', max_length=255),
        ),
        migrations.AlterField(
            model_name='homedetails',
            name='climate_zone',
            field=models.CharField(choices=[('Humid continental', 'Humid continental'), ('Humid subtropical', 'Humid subtropical'), ('Mediterranean', 'Mediterranean'), ('Oceanic (Marine west coast)', 'Oceanic (Marine west coast)'), ('Desert', 'Desert'), ('Semi-arid', 'Semi-arid'), ('Subarctic', 'Subarctic'), ('Tundra', 'Tundra'), ('Ice cap', 'Ice cap'), ('Tropical', 'Tropical'), ('Highland/Alpine', 'Highland/Alpine')], default='Blank', max_length=50),
        ),
        migrations.AlterField(
            model_name='homedetails',
            name='number_of_appliances',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
