# Generated by Django 5.2.7 on 2025-10-10 09:32

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_homedetails_homeowner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedetails',
            name='square_feet',
            field=models.PositiveIntegerField(default=0, validators=[blog.models.validate_non_negative]),
        ),
    ]
