# Generated by Django 5.2.7 on 2025-11-17 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calculator_type",
                    models.CharField(
                        help_text="Type of calculator (e.g., distance, cost, time)",
                        max_length=50,
                    ),
                ),
                ("inputs", models.TextField(help_text="JSON-serialized input values")),
                (
                    "outputs",
                    models.TextField(help_text="JSON-serialized calculation results"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_calculations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="trips_saved_user_id_4e3f24_idx",
                    )
                ],
            },
        ),
    ]
