# Generated by Django 5.1.14 on 2025-11-12 15:03

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeecertification',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='employeecertification',
            name='issued_on',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddConstraint(
            model_name='employeecertification',
            constraint=models.UniqueConstraint(fields=('user', 'cert_type'), name='uniq_user_certtype'),
        ),
    ]
