# Generated by Django 5.2.7 on 2025-11-15 01:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="city",
            new_name="base_city_country_d2c156_idx",
            old_name="city_country_search_idx",
        ),
        migrations.RenameIndex(
            model_name="city",
            new_name="base_city_country_1de310_idx",
            old_name="city_country_slug_idx",
        ),
    ]
