# Generated by Django 5.1.14 on 2025-11-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimeentry',
            name='approved_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
