"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from pathlib import Path as _Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-pf*u6!_@vf51n8hg-cz)de59#29+9+zj*@b3ev3i6cly@+)&6e"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Domain apps
    "apps.calculators",
    "apps.airports",
    "apps.accounts",
    "apps.trips",
    "apps.search",
    "apps.base",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise middleware should be placed directly after SecurityMiddleware
    # so it can serve static files efficiently when enabled in production.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# URL prefix for static files
STATIC_URL = "static/"

# Additional directories to search for static assets during development.
# By default we look for `travelmathlite/static/` so designers and app-level
# assets can be placed there. Can be overridden with the `STATICFILES_DIR`
# environment variable if needed for CI or build pipelines.
STATICFILES_DIRS = [BASE_DIR / "static"]

# Where `collectstatic` places the gathered static assets for deployment.
# Default is `travelmathlite/staticfiles/` but this path can be overridden
# by setting the `STATIC_ROOT` environment variable in CI/deploy.
STATIC_ROOT = _Path(os.getenv("STATIC_ROOT", BASE_DIR / "staticfiles"))

# Media (user-uploaded) files
MEDIA_URL = "/media/"
MEDIA_ROOT = _Path(os.getenv("MEDIA_ROOT", BASE_DIR / "media"))

# Feature flags and static storage policy
# Use ManifestStaticFilesStorage when `USE_MANIFEST_STATIC` is truthy or when
# DEBUG is disabled. This can be toggled via environment for CI/demo runs.
USE_MANIFEST_STATIC = os.getenv("USE_MANIFEST_STATIC", "0").lower() in ("1", "true", "yes")

# Default to manifest storage when DEBUG is False unless explicitly disabled.
if not DEBUG or USE_MANIFEST_STATIC:
    STATICFILES_STORAGE = os.getenv(
        "STATICFILES_STORAGE",
        "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    )

# WhiteNoise tuning
WHITENOISE_MAX_AGE = int(os.getenv("WHITENOISE_MAX_AGE", "31536000"))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Auth settings (ADR-1.0.6)
LOGIN_REDIRECT_URL = "base:index"
LOGOUT_REDIRECT_URL = "base:index"

# Calculators defaults (ADR-1.0.2)
# These can be overridden via environment variables. Defaults chosen for
# reasonable, offline estimates in line with the PRD/ADR.
# - ROUTE_FACTOR: multiplier applied to straight-line distance to approximate
#   driving distance on typical road networks (e.g., 1.2 = 20% longer).
# - AVG_SPEED_KMH: average mixed driving speed used for time estimates.
# - FUEL_PRICE_PER_LITER: default fuel price for cost calculations.
# - FUEL_ECONOMY_L_PER_100KM: default vehicle fuel economy.
ROUTE_FACTOR: float = float(os.getenv("ROUTE_FACTOR", "1.2"))
AVG_SPEED_KMH: float = float(os.getenv("AVG_SPEED_KMH", "80"))
FUEL_PRICE_PER_LITER: float = float(os.getenv("FUEL_PRICE_PER_LITER", "1.50"))
FUEL_ECONOMY_L_PER_100KM: float = float(os.getenv("FUEL_ECONOMY_L_PER_100KM", "7.5"))
