# Generated by Django 4.2.4 on 2023-08-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.TextField(help_text="Checklist item to verify")),
                (
                    "response",
                    models.TextField(help_text="A response to verifiable item"),
                ),
                ("checked", models.BooleanField()),
            ],
        ),
    ]
