# Generated by Django 5.2.7 on 2025-11-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ident",
                    models.CharField(
                        db_index=True,
                        help_text="ICAO or local airport code (primary key from OurAirports)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "iata_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="IATA 3-letter code (preferred for display)",
                        max_length=3,
                    ),
                ),
                ("name", models.CharField(help_text="Airport name", max_length=255)),
                (
                    "airport_type",
                    models.CharField(
                        help_text="Airport type (e.g., large_airport, medium_airport)",
                        max_length=50,
                    ),
                ),
                (
                    "latitude_deg",
                    models.FloatField(help_text="Latitude in decimal degrees"),
                ),
                (
                    "longitude_deg",
                    models.FloatField(help_text="Longitude in decimal degrees"),
                ),
                (
                    "elevation_ft",
                    models.IntegerField(
                        blank=True, help_text="Elevation in feet", null=True
                    ),
                ),
                (
                    "iso_country",
                    models.CharField(
                        db_index=True, help_text="ISO 3166-1 country code", max_length=2
                    ),
                ),
                (
                    "iso_region",
                    models.CharField(
                        blank=True, help_text="ISO 3166-2 region code", max_length=10
                    ),
                ),
                (
                    "municipality",
                    models.CharField(
                        blank=True, help_text="City or town name", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "airports",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["iata_code"], name="airports_iata_co_d51f22_idx"
                    ),
                    models.Index(
                        fields=["iso_country"], name="airports_iso_cou_39e14a_idx"
                    ),
                    models.Index(
                        fields=["latitude_deg", "longitude_deg"],
                        name="airports_latitud_3274f7_idx",
                    ),
                ],
            },
        ),
    ]
