# Generated by Django 5.2.7 on 2025-11-15 01:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airports", "0002_airport_core_integrations"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="airport",
            new_name="airports_country_5e4228_idx",
            old_name="airports_c_country_91032d_idx",
        ),
        migrations.RenameIndex(
            model_name="airport",
            new_name="airports_city_id_572938_idx",
            old_name="airports_c_city_9a0fa2_idx",
        ),
        migrations.RenameIndex(
            model_name="airport",
            new_name="airports_active_4f092f_idx",
            old_name="airports_c_active_368e1b_idx",
        ),
    ]
