# Generated by Django 5.2.6 on 2025-11-03 02:25

import django.utils.timezone
import myblog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the blog post (Max 5MB)', null=True, upload_to=myblog.models.post_image_upload_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish date'),
        ),
    ]
