# Generated by Django 5.2.6 on 2025-11-03 02:28

import myblog.models
import myblog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_post_image_alter_post_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the blog post (Max 5MB, JPG/PNG/GIF/WebP)', null=True, upload_to=myblog.models.post_image_upload_path, validators=[myblog.validators.ImageValidator(), myblog.validators.validate_image_content]),
        ),
    ]
